### ISSUE TITLE
Provide an instruction how to compile/preview the tutorial?

### ISSUE THREAD

**Issue by madjestic** [rlupton20/yampaTutorial#1]
It looks like LaTeX, but \hask tags and others are causing errors.  Which extension is this?  Or is it parsed by something else (HaTeX perhapse?)

Thanks,
Vlad

**Comment by rlupton20** [comment]
Hi Vlad,

sorry I didn't receive any notification of your issue, and so sorry for the late reply. You should be able to build it with LaTeX, the \hask command is just a macro for \texttt. How are you trying to build?
`pdflatex yampa.tex`
should do it.

The tutorial is far from completion I'll add, and is in need of some serious editing. I'd be interested in any feedback you might have. That said, with what has been written, other "tutorials" might make a lot more sense (and be usable).

**Comment by rlupton20** [comment]
I also use the Fira font set, so you might want to install that or just comment out its use. All packages and macros are declared in yampa.tex, so that should be informative or good to adjust.

Hope that helps!

**Comment by madjestic** [comment]
Thanks, I'll try.

**Comment by madjestic** [comment]
Thanks again, that takes one step closer.  I tried running pdflatex yampa.tex, and now I am getting this:

```
kpathsea: Running mktexmf bchr7t
! I can't find file `bchr7t'.
<*> ...:=ljfour; mag:=1; nonstopmode; input bchr7t

Please type another input file name
! Emergency stop.
<*> ...:=ljfour; mag:=1; nonstopmode; input bchr7t

Transcript written on mfput.log.
grep: bchr7t.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input bchr7t' failed to make bchr7t.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font OT1/bch/m/n/10=bchr7t at 10.0pt not loadable: Metric (TFM) file not foun
d.
<to be read again> 
                   relax 
l.14 \begin{document}
```

It looks like bchr7t is missing.  Could you provide the file, or a suggestion how to fix?

Thanks,
Vlad

**Comment by madjestic** [comment]
K, it looks like commenting out \usepackage{charter} does the trick.
Sorry for disturbance.

Cheers!

**Comment by rlupton20** [comment]
Sorry, yes it also uses the charter font set. I'm surprised it didn't make the lack of the charter package more explicit, though. Perhaps it's something wrong in your particular set up?

Apologies for the lack of prompt reply, I've been kind of busy as of late. I'm glad you got it to build in the end.

**Comment by madjestic** [comment]
I do not know what can be wrong with my set up, other than fonts in GNU/Linux being a black magic with headless chicken running around spitting blood.  No problem with the lack of prompt.  We all do what we can when we can.
